// AI Lessons — the "memory" half of Pinned's product loop.
//
// When Pinned learns something (a real-catch guard, a blocked Guard
// Integrity attempt, a confirmed sibling audit), it appends a short
// rule to `.pinned/ai-lessons.md`. That file gets pointed at by
// agent-config files (CLAUDE.md, .cursorrules, etc.) so future AI
// coders reading the repo see the rules they must not break.
//
// See [[strategic-pivot-guard-integrity]] for product framing.
// See [[readme-rewrite-spec]] for the canonical file format.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

export type LessonKind = "real-catch" | "guard-block" | "sibling-confirmed" | "baseline";

export type LessonInput = {
  /** Stable id of the guard this lesson is rooted in (e.g. "client-getReport-authHeaders"). */
  guardId: string;
  /** Short markdown title for the lesson section. e.g. "Auth headers in protected API calls" */
  title: string;
  /** Concrete description of the bug that triggered this lesson. */
  pastMistake: string;
  /** The rule a future AI coder must follow. */
  rule: string;
  /** ≤80 char one-sentence summary used by the statusline LEARNED display. */
  plainEnglish: string;
  /** Where this lesson came from. */
  kind: LessonKind;
  /**
   * 0.2.25+: AI model that caused this lesson (when detectable).
   * Format: `<provider>:<family>:<version>` for known, "unspecified-model"
   * for unknown. Used by paid-tier provider-mistake analytics. Lessons
   * SURFACE TO ALL MODELS — the tag is for analytics + filtering, not
   * gating which AI sees the rule.
   */
  aiModel?: string;
  /** 0.2.25+: tool/agent surface that wrote the buggy code. */
  aiTool?: string;
};

export type AiLessonsConfig = {
  /** Repo root. Default: process.cwd(). */
  repoRoot?: string;
  /** Path to the lessons file, relative to repoRoot. Default: ".pinned/ai-lessons.md". */
  filePath?: string;
};

const DEFAULT_FILE = ".pinned/ai-lessons.md";
const HEADER = `# Pinned AI Lessons

> Repo-specific rules for AI coding agents (Claude, Cursor, Devin, etc.).
> Generated by Pinned from real bug fixes, blocked Guard Integrity attempts, and confirmed sibling audits.
> **Do not weaken, skip, or delete pinned tests in \`tests/pinned/\`.**

`;

// Per-entry layout. The "<!-- pinned:guard=... -->" marker is the
// dedupe key — re-adding a lesson for the same guard updates the
// "Past mistake" list rather than appending a duplicate section.
function renderLesson(input: LessonInput): string {
  return [
    `## ${input.title}`,
    "",
    `<!-- pinned:guard=${input.guardId} kind=${input.kind} -->`,
    "",
    `**Past mistake:**`,
    input.pastMistake,
    "",
    `**Rule:**`,
    input.rule,
    "",
    `**Guard:** \`${input.guardId}\``,
    "",
    `**Plain English:** ${input.plainEnglish}`,
    "",
  ].join("\n");
}

// Match either an existing section for the same guardId (in which
// case we append evidence) or no match (append a new section).
function findExistingSection(body: string, guardId: string): { start: number; end: number } | null {
  const markerRe = new RegExp(`<!-- pinned:guard=${guardId.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")} kind=[^>]+ -->`);
  const m = markerRe.exec(body);
  if (!m) return null;
  // Section starts at the most-recent "## " before the marker
  const headerStart = body.lastIndexOf("\n## ", m.index);
  const start = headerStart === -1 ? 0 : headerStart + 1;
  // Section ends at the next "\n## " (or end of file)
  const nextHeader = body.indexOf("\n## ", m.index);
  const end = nextHeader === -1 ? body.length : nextHeader + 1;
  return { start, end };
}

// Append a new "Past mistake:" bullet inside an existing entry rather
// than creating a duplicate section. Keeps the lessons file from
// growing per repeated AI bypass attempts on the same guard.
function appendEvidenceToSection(section: string, newMistake: string): string {
  // Find the existing "**Past mistake:**" line and append after the
  // following content block.
  const pmIdx = section.indexOf("**Past mistake:**");
  if (pmIdx === -1) return section; // malformed; leave alone
  // Find the next blank line after the past-mistake heading
  const afterPm = section.indexOf("\n\n", pmIdx);
  if (afterPm === -1) return section;
  const insertion = `\n- ${newMistake}`;
  return section.slice(0, afterPm) + insertion + section.slice(afterPm);
}

export type AppendResult = {
  added: boolean;             // true if a new section was created
  updated: boolean;           // true if an existing section was extended with new evidence
  filePath: string;
  plainEnglish: string;
  guardId: string;
};

// Machine-readable sidecar for the markdown lessons file. Tools that
// want structured access (Pinned itself, Claude hooks, Cursor rules,
// future CI integrations) read this instead of parsing markdown.
// Per [[tier-model-final-2026-05-23]] — "make lessons machine-readable too".
const DEFAULT_JSON_FILE = ".pinned/lessons.json";

export type LessonJsonEntry = {
  id: string;
  rule: string;
  guards: string[];
  appliesTo?: string[];
  severity: "block" | "warn";
  plainEnglish: string;
  pastMistakes: string[];
  updatedAt: string;
  /**
   * 0.2.25+: Per-AI-model occurrence breakdown. Useful for paid-tier
   * provider-mistake analytics. Empty when no signal; aggregates over
   * repeated catches when ≥1 model is identifiable.
   */
  byModel?: Record<string, { hits: number; firstSeen: string; lastSeen: string; tool?: string }>;
};

function syncLessonsJson(repoRoot: string, jsonPath: string, entry: LessonInput): void {
  const abs = join(repoRoot, jsonPath);
  mkdirSync(dirname(abs), { recursive: true });
  let payload: { version: 1; lessons: LessonJsonEntry[] } = { version: 1, lessons: [] };
  try {
    if (existsSync(abs)) {
      const parsed = JSON.parse(readFileSync(abs, "utf8"));
      if (parsed && Array.isArray(parsed.lessons)) payload = parsed;
    }
  } catch { /* corrupt → reset */ }
  const now = new Date().toISOString();
  const existingIdx = payload.lessons.findIndex((l) => l.id === entry.guardId);
  if (existingIdx >= 0) {
    const existing = payload.lessons[existingIdx];
    if (!existing.pastMistakes.includes(entry.pastMistake)) {
      existing.pastMistakes.push(entry.pastMistake);
    }
    existing.updatedAt = now;
    // 0.2.25+ per-model rollup. Adds to existing model entry, or
    // initializes a new one. Never overwrites the firstSeen date.
    if (entry.aiModel) {
      const byModel = existing.byModel ?? {};
      const prev = byModel[entry.aiModel] ?? { hits: 0, firstSeen: now, lastSeen: now };
      byModel[entry.aiModel] = {
        hits: prev.hits + 1,
        firstSeen: prev.firstSeen,
        lastSeen: now,
        ...(entry.aiTool ? { tool: entry.aiTool } : {}),
      };
      existing.byModel = byModel;
    }
    payload.lessons[existingIdx] = existing;
  } else {
    payload.lessons.push({
      id: entry.guardId,
      rule: entry.rule,
      guards: [entry.guardId],
      severity: "block",
      plainEnglish: entry.plainEnglish,
      pastMistakes: [entry.pastMistake],
      updatedAt: now,
      ...(entry.aiModel ? {
        byModel: {
          [entry.aiModel]: {
            hits: 1,
            firstSeen: now,
            lastSeen: now,
            ...(entry.aiTool ? { tool: entry.aiTool } : {}),
          },
        },
      } : {}),
    });
  }
  writeFileSync(abs, JSON.stringify(payload, null, 2) + "\n");
}

export function readLessonsJson(cfg: AiLessonsConfig = {}): LessonJsonEntry[] {
  const root = cfg.repoRoot ?? process.cwd();
  const abs = join(root, DEFAULT_JSON_FILE);
  if (!existsSync(abs)) return [];
  try {
    const parsed = JSON.parse(readFileSync(abs, "utf8"));
    if (parsed && Array.isArray(parsed.lessons)) return parsed.lessons;
  } catch { /* */ }
  return [];
}

export function appendLesson(input: LessonInput, cfg: AiLessonsConfig & { statusCacheDir?: string } = {}): AppendResult {
  const root = cfg.repoRoot ?? process.cwd();
  const rel = cfg.filePath ?? DEFAULT_FILE;
  const abs = join(root, rel);
  mkdirSync(dirname(abs), { recursive: true });

  let body = existsSync(abs) ? readFileSync(abs, "utf8") : HEADER;
  if (!body.startsWith("# Pinned AI Lessons")) {
    // File exists but doesn't have our header (legacy/manual). Prepend.
    body = HEADER + body;
  }

  const existing = findExistingSection(body, input.guardId);
  let added = false;
  let updated = false;
  if (existing) {
    const section = body.slice(existing.start, existing.end);
    // Only update if the new past-mistake text isn't already present
    if (!section.includes(input.pastMistake)) {
      const updatedSection = appendEvidenceToSection(section, input.pastMistake);
      body = body.slice(0, existing.start) + updatedSection + body.slice(existing.end);
      updated = true;
    }
  } else {
    if (!body.endsWith("\n")) body += "\n";
    body += renderLesson(input);
    added = true;
  }

  writeFileSync(abs, body);

  // Sync the machine-readable JSON sidecar so tools (Claude hooks,
  // Cursor rules, future CI integrations) have structured access
  // without parsing markdown.
  try {
    syncLessonsJson(root, DEFAULT_JSON_FILE, input);
  } catch { /* best-effort */ }

  // Emit a LEARNED status event so the statusline shows "Pinned ·
  // LEARNED · <plainEnglish>" for ~2 min, then falls back to the
  // baseline "N pins · M lessons" display. Only fires when we
  // actually added new content (no event for pure-noop dedupe).
  if (added || updated) {
    try {
      const total = readLessons({ repoRoot: root, filePath: rel }).count;
      const statusDir = cfg.statusCacheDir ?? join(root, "tests/pinned");
      // Dynamic import — keeps aiLessons.ts standalone-testable
      // without statusline as a hard dep at module-load time.
      import("./statusline.js")
        .then((mod) => mod.recordLessonLearned(statusDir, { plainEnglish: input.plainEnglish, totalCount: total }))
        .catch(() => { /* best-effort */ });
    } catch {
      /* best-effort */
    }
  }

  return { added, updated, filePath: rel, plainEnglish: input.plainEnglish, guardId: input.guardId };
}

// Read the full set of lessons currently in the file. Used for the
// statusline baseline count ("PASS · N guards · M lessons") and for
// `pinned audit --learned` to know what patterns have been learned.
export type ReadLessonsResult = {
  count: number;
  guardIds: string[];
};

export function readLessons(cfg: AiLessonsConfig = {}): ReadLessonsResult {
  const root = cfg.repoRoot ?? process.cwd();
  const rel = cfg.filePath ?? DEFAULT_FILE;
  const abs = join(root, rel);
  if (!existsSync(abs)) return { count: 0, guardIds: [] };
  const body = readFileSync(abs, "utf8");
  const re = /<!-- pinned:guard=([^\s]+) kind=[^>]+ -->/g;
  const ids: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(body)) !== null) ids.push(m[1]);
  return { count: ids.length, guardIds: ids };
}
